### PR TITLE
add algorithm for determining activities

### PR DESCRIPTION
**Pull request by hustjl22**
Added the algorithm for determining activities, could use some help.  Wanted to show you the code though.  Right now it calls the determineActivity() whenever the history button is pressed.  Just for testing.  Still need to add automatically doing this every 2 minutes.

@tnycum

### CODE REVIEW

**Comment by tnycum** [comment]
I think the way you are distinguishing activities is probably fine, though I haven't tested it on my phone. 

One key part in the project description is that the activities are determined in two minute intervals. Maybe what we could do is keep a two minute history of guesses at what the current activity is (calling determineActivity every 100 or so sensor samples), and whatever the majority guess is what is displayed as the current activity. Then at two minutes the history is cleared.

**Comment by hustjl22** [comment]
What do you think the best way is to do the timing of 2 minutes?

**Comment by hustjl22** [comment]
I changed the algorithms a little bit.  It seems to be a little better.  Service determines the activity every 2 minutes, and the activity pulls the history every 2 minutes.  I could not get the ListView to refresh after pulling data.  And it didn't actually write history to the SD card.  We might not need the ListView in the UI from the assignment description, but I like it if we can get it to work.

**Comment by tnycum** [comment]
Yeah to get it to refresh you have to call adapter.notifyDataSetChanged() after adding activities to the arraylist.

**Comment by tnycum** [comment]
So I got the activity history to save to 'external' storage. It's not on the SD card but I think what the professor means by external storage is just external to the app itself. I am using 'getExternalFilesDir()' to find the directory to write to. Apparently writing to the SD card is a lot more difficult because there are different APIs for different cards/phones. Will push my changes soon.

**Comment by hustjl22** [comment]
I thought I tried calling adapter.notifyDataSetChanged().  It might be because I didn't just add items, but actually just set the array to a whole new one.  We can ask him about the SD card in class tomorrow just to be sure.  I'm going to merge this in.

**Pull request merged**
